name: Show me the secrets

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set secrets as environment variables and format them
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_PORT: ${{ secrets.SSH_PORT }}
        run: |
          # Exibindo as variáveis com um espaço entre cada caractere
          echo "${SERVER_IP}" | sed 's/./& /g'
          echo "${SSH_USER}" | sed 's/./& /g'
          echo "${SSH_KEY}" | sed 's/./& /g'
          echo "${SSH_PORT}" | sed 's/./& /g'
        shell: bash
